### ISSUE TITLE
Feature: fire job delayed, only initially

### ISSUE THREAD

**Issue by mdbergmann** [lisp-maintainers/clerk#1]
When scheduling a job I'd sometimes want that it fires delayed. Only initially, before it recurs ('every'), but this would also be applicable to jobs that fire only once. So an 'initial-delay'.

**Comment by BnMcGn** [comment]
Hi Manfred,

I'll look it over.

**Comment by BnMcGn** [comment]
I think would make sense to reuse the :in keyword for this, eg:

`(job "do something" :in :3.seconds :every :1.second (something))`

:after might work nicely too.

`(job "do something" :after :3.seconds :every :1.second (something))`

**Comment by mdbergmann** [comment]
Yeah, both would work OK I think.

**Comment by BnMcGn** [comment]
Implemented. Give it a spin.

**Comment by mdbergmann** [comment]
I've tested a bit. For a one time job this isn't implemented, but it doesn't make sense to be. So that's OK.
On a recurring job the `:in` or `:after` gives an initial delay.
So looks good.
